command:
  - npm
  - run
  - start

env:
  - name: APP_TITLE
    value: 'Ingestao Governada'
  - name: APP_ENV
    value: 'production'
  - name: NODE_ENV
    value: 'production'
  - name: DATABRICKS_HOST
    value: 'https://dbc-c9eab3b3-1f5f.cloud.databricks.com'
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    value: '4e4f36c4c611f1d3'
  - name: UC_CATALOG
    value: 'cm_dbx_dev'
  - name: GOV_SYS_CTRL_SCHEMA
    value: 'cm_dbx_dev.ingestion_sys_ctrl'
  - name: GOV_SYS_OPS_SCHEMA
    value: 'cm_dbx_dev.ingestion_sys_ops'
  - name: PORTAL_URL
    value: 'https://ingestao-governada-3958128530848672.aws.databricksapps.com'
  - name: DATABRICKS_ORCHESTRATOR_JOB_ID
    value: '690887429046802'
  - name: DATABRICKS_TOKEN
    valueFrom: 'ingestao-governada/databricks-token'
